# Welcome to Jekyll!
#

# Site settings
title: Dowsnux
description: Agencia de desenvolvimento de aplivativos Android e iOs
owner: Dowsnux
first_published: 2020
email: dowsnux@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://franciscotavares.github.io/" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/fcoanjos
  github: https://github.com/FranciscoTavares
  linkedin-square: https://linkedin.com/in/fcoanjos
  facebook-official: 
  google-plus-square: 
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
